#!/usr/bin/env node

'use strict';

var fs = require( 'fs' );
var path = require( 'path' );
var packageJson = require( '../package.json' );
var sass = require( 'sass' );
var terser = require( 'terser' );

var root = path.resolve( __dirname, '..' );
var sourceJsDirectory = getProjectPath( packageJson.source.js );
var sourceAdminJsDirectory = getProjectPath( packageJson.source.adminJs );
var sourceSassDirectory = getProjectPath( packageJson.source.sass );
var targetJsDirectory = getProjectPath( packageJson.target.js );
var targetCssDirectory = getProjectPath( packageJson.target.css );
var targetJsFile = path.join( targetJsDirectory, packageJson.name + '.js' );
var targetAdminJsFile = path.join(
	targetJsDirectory,
	packageJson.name + '-admin.js'
);

function getProjectPath( projectPath ) {
	return path.resolve( root, projectPath );
}

function parseArgs( argv ) {
	var mode = 'dev';
	var watch = false;
	var i;

	for ( i = 2; i < argv.length; i++ ) {
		if ( argv[ i ] === 'dev' || argv[ i ] === 'prod' ) {
			mode = argv[ i ];
		} else if ( argv[ i ] === '--watch' ) {
			watch = true;
		}
	}

	return {
		mode: mode,
		watch: watch,
	};
}

function ensureDirectory( directory ) {
	if ( ! fs.existsSync( directory ) ) {
		fs.mkdirSync( directory, { recursive: true } );
	}
}

function getFiles( directory, extension, excludedDirectories ) {
	var entries;
	var files = [];
	var i;
	var entryPath;

	if ( ! fs.existsSync( directory ) ) {
		return files;
	}

	entries = fs.readdirSync( directory, { withFileTypes: true } );

	for ( i = 0; i < entries.length; i++ ) {
		entryPath = path.join( directory, entries[ i ].name );

		if ( entries[ i ].isDirectory() ) {
			if ( excludedDirectories.indexOf( entryPath ) === -1 ) {
				files = files.concat(
					getFiles( entryPath, extension, excludedDirectories )
				);
			}
		} else if (
			entries[ i ].isFile() &&
			path.extname( entries[ i ].name ) === extension
		) {
			files.push( entryPath );
		}
	}

	files.sort();

	return files;
}

function removeFile( file ) {
	if ( fs.existsSync( file ) ) {
		fs.unlinkSync( file );
	}
}

function getTerserInput( files ) {
	var input = {};
	var i;

	for ( i = 0; i < files.length; i++ ) {
		input[ path.relative( root, files[ i ] ) ] = fs.readFileSync(
			files[ i ],
			'utf8'
		);
	}

	return input;
}

async function buildJavaScript(
	sourceDirectory,
	targetFile,
	mode,
	excludedDirectories
) {
	var files = getFiles( sourceDirectory, '.js', excludedDirectories || [] );
	var sourceMapFile = targetFile + '.map';
	var result;

	ensureDirectory( targetJsDirectory );

	if ( files.length === 0 ) {
		removeFile( targetFile );
		removeFile( sourceMapFile );
		console.log(
			'No JavaScript sources found in ' +
				path.relative( root, sourceDirectory ) +
				'.'
		);
		return;
	}

	result = await terser.minify( getTerserInput( files ), {
		compress: mode === 'prod',
		mangle: mode === 'prod',
		format: {
			beautify: mode !== 'prod',
			comments: false,
			preamble:
				'/* Generated by scripts/build-assets.js. Do not edit directly. */',
		},
		sourceMap:
			mode === 'prod'
				? false
				: {
						filename: path.basename( targetFile ),
						url: path.basename( sourceMapFile ),
				  },
	} );

	if ( ! result.code ) {
		throw new Error( 'JavaScript build did not produce output.' );
	}

	fs.writeFileSync( targetFile, result.code + '\n', 'utf8' );

	if ( mode === 'prod' ) {
		removeFile( sourceMapFile );
	} else {
		fs.writeFileSync( sourceMapFile, result.map, 'utf8' );
	}

	console.log(
		'Built ' +
			path.relative( root, targetFile ) +
			' from ' +
			files.length +
			' source file(s). Mode: ' +
			mode
	);
}

function buildSassFile( sourceFile, mode ) {
	var relativePath = path.relative( sourceSassDirectory, sourceFile );
	var targetFile = path.join(
		targetCssDirectory,
		relativePath.replace( /\.scss$/, '.css' )
	);
	var sourceMapFile = targetFile + '.map';
	var result;

	ensureDirectory( path.dirname( targetFile ) );

	result = sass.compile( sourceFile, {
		sourceMap: mode !== 'prod',
		style: mode === 'prod' ? 'compressed' : 'expanded',
	} );

	fs.writeFileSync(
		targetFile,
		result.css +
			( mode === 'prod'
				? ''
				: '\n/*# sourceMappingURL=' +
				  path.basename( sourceMapFile ) +
				  ' */' ) +
			'\n',
		'utf8'
	);

	if ( mode === 'prod' ) {
		removeFile( sourceMapFile );
	} else {
		fs.writeFileSync(
			sourceMapFile,
			JSON.stringify( result.sourceMap ),
			'utf8'
		);
	}

	console.log(
		'Built ' + path.relative( root, targetFile ) + '. Mode: ' + mode
	);
}

function copySassAssets() {
	var files = getFiles( sourceSassDirectory, '.gif', [] );
	var i;
	var targetFile;

	for ( i = 0; i < files.length; i++ ) {
		targetFile = path.join(
			targetCssDirectory,
			path.relative( sourceSassDirectory, files[ i ] )
		);
		ensureDirectory( path.dirname( targetFile ) );
		fs.copyFileSync( files[ i ], targetFile );
	}
}

function removeObsoleteAssetOutputs() {
	removeFile( path.join( targetCssDirectory, packageJson.name + '.css' ) );
	removeFile(
		path.join( targetCssDirectory, packageJson.name + '.css.map' )
	);
	removeFile( path.join( targetCssDirectory, 'spinner.gif' ) );
}

function buildSass( mode ) {
	var files = getFiles( sourceSassDirectory, '.scss', [] ).filter(
		function filterSassPartials( file ) {
			return path.basename( file ).charAt( 0 ) !== '_';
		}
	);
	var i;

	ensureDirectory( targetCssDirectory );
	removeObsoleteAssetOutputs();

	for ( i = 0; i < files.length; i++ ) {
		buildSassFile( files[ i ], mode );
	}

	copySassAssets();
}

function buildAssets( mode ) {
	return buildJavaScript( sourceJsDirectory, targetJsFile, mode, [
		sourceAdminJsDirectory,
	] )
		.then( function onJavaScriptBuilt() {
			return buildJavaScript(
				sourceAdminJsDirectory,
				targetAdminJsFile,
				mode,
				[]
			);
		} )
		.then( function onAdminJavaScriptBuilt() {
			buildSass( mode );
		} );
}

function watchDirectory( directory, name ) {
	if ( ! fs.existsSync( directory ) ) {
		return;
	}

	fs.watch( directory, { recursive: true }, function onAssetChange() {
		buildAssets( 'dev' ).catch( function onBuildError( error ) {
			console.error( error );
		} );
	} );

	console.log(
		'Watching ' +
			path.relative( root, directory ) +
			' for ' +
			name +
			' changes.'
	);
}

function main() {
	var args = parseArgs( process.argv );

	buildAssets( args.mode )
		.then( function onAssetsBuilt() {
			if ( args.watch ) {
				watchDirectory( sourceJsDirectory, 'JavaScript' );
				watchDirectory( sourceAdminJsDirectory, 'admin JavaScript' );
				watchDirectory( sourceSassDirectory, 'Sass' );
			}
		} )
		.catch( function onBuildError( error ) {
			console.error( error );
			process.exitCode = 1;
		} );
}

main();
